src/Entity/Connect/Categories.php
<?php

namespace App\Entity\Connect;

use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use ApiPlatform\Core\Annotation\ApiResource;
use App\Entity\Connect\MonSac;

/**
 * @ORM\Entity(repositoryClass=CategoriesRepository::class)
 * @ApiResource
 */
class Categories
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(type="string", length=255)
     */
    private $Slug;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="categories")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Categories::class, mappedBy="parent")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=MonSac::class, mappedBy="categories")
     */
    private $MonSac;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->MonSac = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(self $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setParent($this);
        }

        return $this;
    }

    public function removeCategory(self $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getParent() === $this) {
                $category->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MonSac[]
     */
    public function getMonSac(): Collection
    {
        return $this->MonSac;
    }

    public function addSacado(MonSac $sacado): self
    {
        if (!$this->MonSac->contains($sacado)) {
            $this->MonSac[] = $sacado;
            $sacado->setCategories($this);
        }

        return $this;
    }

    public function removeSacado(MonSac $sacado): self
    {
        if ($this->MonSac->removeElement($sacado)) {
            // set the owning side to null (unless already changed)
            if ($sacado->getCategories() === $this) {
                $sacado->setCategories(null);
            }
        }

        return $this;
    }
    
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function addMonSac(MonSac $monSac): self
    {
        if (!$this->MonSac->contains($monSac)) {
            $this->MonSac[] = $monSac;
            $monSac->setCategories($this);
        }

        return $this;
    }

    public function removeMonSac(MonSac $monSac): self
    {
        if ($this->MonSac->removeElement($monSac)) {
            // set the owning side to null (unless already changed)
            if ($monSac->getCategories() === $this) {
                $monSac->setCategories(null);
            }
        }

        return $this;
    }
}

src/Entity/Connect/Voyages.php
<?php

namespace App\Entity\Connect;

use App\Repository\VoyagesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Gedmo\Mapping\Annotation as Gedmo;
use App\Entity\Users;
use App\Entity\Main\Pays;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=VoyagesRepository::class)
 */
class Voyages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="voyages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateTime_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateTime_fin;

    /**
     * @ORM\Column(type="integer")
     */
    private $participantNbAdultes;

    /**
     * @ORM\Column(type="integer")
     */
    private $participantNbEnfants;

    /**
     * @ORM\ManyToMany(targetEntity=Pays::class, inversedBy="voyages")
     */
    private $pays;

    public function __construct()
    {
        $this->pays = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateTimeDebut(): ?\DateTimeInterface
    {
        return $this->dateTime_debut;
    }

    public function setDateTimeDebut(\DateTimeInterface $dateTime_debut): self
    {
        $this->dateTime_debut = $dateTime_debut;

        return $this;
    }

    public function getDateTimeFin(): ?\DateTimeInterface
    {
        return $this->dateTime_fin;
    }

    public function setDateTimeFin(\DateTimeInterface $dateTime_fin): self
    {
        $this->dateTime_fin = $dateTime_fin;

        return $this;
    }

    public function getParticipantNbAdultes(): ?int
    {
        return $this->participantNbAdultes;
    }

    public function setParticipantNbAdultes(int $participantNbAdultes): self
    {
        $this->participantNbAdultes = $participantNbAdultes;

        return $this;
    }

    public function getParticipantNbEnfants(): ?int
    {
        return $this->participantNbEnfants;
    }

    public function setParticipantNbEnfants(int $participantNbEnfants): self
    {
        $this->participantNbEnfants = $participantNbEnfants;

        return $this;
    }

    /**
     * @return Collection|Pays[]
     */
    public function getPays(): Collection
    {
        return $this->pays;
    }

    public function addPay(Pays $pay): self
    {
        if (!$this->pays->contains($pay)) {
            $this->pays[] = $pay;
        }

        return $this;
    }

    public function removePay(Pays $pay): self
    {
        $this->pays->removeElement($pay);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/Connect/ConnectController.php
<?php

namespace App\Controller\Connect;

use App\Entity\Connect\Categories;
use App\Entity\Connect\MonSac;
use App\Form\CategoriesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/connect", name="connect_")
 * @package App\Controller
 */
class ConnectController extends AbstractController
{
    /**
     * 
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        return $this->render('connect/index.html.twig', [
            'controller_name' => 'connect_home',
        ]);
    }

}

src/Controller/Connect/ContactController.php
<?php

namespace App\Controller\Connect;

use App\Entity\Connect\Categories;
use App\Entity\Connect\MonSac;
use App\Form\CategoriesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/connect/contact", name="connect_contact_")
 * @package App\Controller
 */
class ContactController extends AbstractController
{
    /**
     * 
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        return $this->render('connect/contact/index.html.twig', [
            'controller_name' => 'AdminController',
        ]);
    }

}

src/Controller/Connect/MonSacController.php
<?php

namespace App\Controller\Connect;

use App\Entity\Connect\MonSac;
use App\Repository\MonSacRepository;
use App\Form\EditProfileType;
use App\Form\MonSacType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/connect/monsac", name="connect_monsac_")
 * @package App\Controller
 */
class MonSacController extends AbstractController
{

    public $listeEtat = ['Pourquoi pas', 'A acheter', 'Acheté'];

    /**
    * 
    * @Route("/", name="home")
    */
   public function index(MonsacRepository $monsacRepo)
   {
       $sens = "DESC";
       $search = "";
       $listeEtat = ['Pourquoi pas', 'A acheter', 'Acheté'];


       $Donnees = $monsacRepo->findOneBy(['users' => $this->getUser()]);

       return $this->render('connect/monsac/index.html.twig', [
           'Donnees' => $Donnees,
           'sens1' => $sens,
           'find' => $search,
           'listeEtat' => $listeEtat,
           'controller_name' => 'connect_monsac_',
       ]);
   }


    /**
     * 
     * @Route("/tri/{col}/{sens}", name="tri")
     */
    public function tri(MonsacRepository $monsacRepo, $col, $sens)
    {
        $sens1 = "DESC";
        $search = "";
        $listeEtat = ['Pourquoi pas', 'A acheter', 'Acheté'];

        $repository = $this->getDoctrine()->getRepository(Monsac::class);
        $listDonnees = $repository->findBy(array(), array($col => $sens),     null,     null);

        if ($sens == $sens1) {
            $sens1 = "ASC";
        }

        return $this->render('admin/monsac/index.html.twig', [
            'Donnees' => $listDonnees,
            'sens1' => $sens1,
            'find' => $search,
            'listeEtat' => $listeEtat,
            'controller_name' => 'connect_monsac_',
        ]);
    }





    /**
     * @Route("/ajout", name="ajout")
     */
    public function ajoutMonSac(Request $request): Response
    {
        $MonSac = new MonSac;

        $form =$this->createForm(MonSacType::class, $MonSac);
        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()){

            $em = $this->getDoctrine()->getManager();

            $MonSac->setUsers($this->getUser());
            $MonSac->setActive(false);
            
            $em->persist($MonSac);
            $em->flush();

            return $this->redirectToRoute('admin_home');
        }

        return $this->render('connect/MonSac/ajout.html.twig', [
            'form' => $form->createView(),
            'controller_name' => 'connect_monsac_',
        ]);
    }

}

src/Controller/Connect/VoyagesController.php
<?php

namespace App\Controller\Connect;

use App\Entity\Connect\Voyages;
use App\Repository\VoyagesRepository;
use App\Form\EditProfileType;
use App\Form\VoyagesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/connect/voyages", name="connect_voyages_")
 * @package App\Controller
 */
class VoyagesController extends AbstractController
{

    public $listeEtat = ['Pourquoi pas', 'A acheter', 'Acheté'];

    /**
    * 
    * @Route("/", name="home")
    */
   public function index(VoyagesRepository $voyagesRepo)
   {
       $sens = "DESC";
       $search = "";

       $Donnees = $voyagesRepo->findOneBy(['users' => $this->getUser()]);

       return $this->render('connect/voyages/index.html.twig', [
           'Donnees' => $Donnees,
           'sens1' => $sens,
           'find' => $search,
           'controller_name' => 'connect_voyages_',
       ]);
   }


    /**
     * 
     * @Route("/tri/{col}/{sens}", name="tri")
     */
    public function tri(VoyagesRepository $voyagesRepo, $col, $sens)
    {
        $sens1 = "DESC";
        $search = "";
        $listeEtat = ['Pourquoi pas', 'A acheter', 'Acheté'];

        $repository = $this->getDoctrine()->getRepository(Voyages::class);
        $listDonnees = $repository->findBy(array(), array($col => $sens),     null,     null);

        if ($sens == $sens1) {
            $sens1 = "ASC";
        }

        return $this->render('admin/voyages/index.html.twig', [
            'Donnees' => $listDonnees,
            'sens1' => $sens1,
            'find' => $search,
            'controller_name' => 'connect_voyages_',
        ]);
    }





    /**
     * @Route("/ajout", name="ajout")
     */
    public function ajoutVoyages(Request $request): Response
    {
        $voyages = new Voyages;

        $form =$this->createForm(VoyagesType::class, $voyages);
        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()){

            $em = $this->getDoctrine()->getManager();

            $voyages->setUsers($this->getUser());
         //   $voyages->setActive(false);
            
            $em->persist($voyages);
            $em->flush();

            return $this->redirectToRoute('connect_voyages_');
        }

        return $this->render('connect/voyages/ajout.html.twig', [
            'form' => $form->createView(),
            'controller_name' => 'connect_voyages_',
        ]);
    }

}

templates/connect/voyages/ajout.html.twig
{% extends 'baseConnect.html.twig' %}

{% block title %}Ajout user{% endblock %}

{% block body %}
    <h1>Ajouter un produit dans mon sac à dos.</h1>
    {{ form(form) }}


{% endblock %}

templates/connect/voyages/index.html.twig
{% extends 'baseConnect.html.twig' %}

{% block title %}Mes voyages!{% endblock %}

{% block body %}
	<style>
		.example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
		.example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
			.btn { font-size: 10px !important; }
	</style>


<h1>Gérer mes voyages :</h1>
  <div class="grix xs4">
    <div>
    	<a href="{{ path("admin_voyages_ajout") }}" class="btn blue">Ajouter un voyage</a>
	</div>
  </div>
<div class="grix xs2 md4 lg4">
  	<div></div>
  	<div><form action="{{ path("admin_voyages_recherche") }}" method="post"></div>
    <div>
      <input type="text" name="find" value="{{ find }}" style='width:100%;' class="form-control rounded-1">
    </div>
	<div>
		<input type="submit" class="btn shadow-1 rounded-1 small primary uppercase" value="Recherche">
		</form>
		{% if find != "" %}
			<b><a href='{{ path("admin_voyages_home") }}'>retour à toute la liste</a></b>
		{% endif %}
	</div>
  </div>


{% if Donnees|length > 0 %}
	<table class="table striped" id="dataTable">
		<thead>
			<tr>
			    <th>
					<input type="checkbox" onchange="selectForm(this);"  checked name="selectAll" value="1"/>
				</th>
				<th><a href='{{ path("admin_voyages_tri", {col: 'created_at', sens: sens1}) }}'>Création</a></th>
                <th><a href='{{ path("admin_voyages_tri", {col: 'titre', sens: sens1}) }}'>Titre</a></th>
				<th><a href='{{ path("admin_voyages_tri", {col: 'dateTime_debut', sens: sens1}) }}'>Debut</a></th>
				<th><a href='{{ path("admin_voyages_tri", {col: 'dateTime_fin', sens: sens1}) }}'>Fin</a></th>
				<th><a href='{{ path("admin_voyages_tri", {col: 'participantNbAdultes', sens: sens1}) }}'>Adultes</a></th>
				<th><a href='{{ path("admin_voyages_tri", {col: 'participantNbEnfants', sens: sens1}) }}'>Enfants</a></th>
				<th><a href='{{ path("admin_voyages_tri", {col: 'pays', sens: sens1}) }}'>Pays</a></th>
				
			</tr>
		</thead>
		<tbody>
        {% for Donne in Donnees %}            
			<tr>
			    <td>
					<label class="form-check">
					<input type="checkbox" checked name="recordsCheckBox[]" value="{{ Donne.id }}"/>
					</label>
				</td>
                <td>{{Donne.createdAt|date("d/m/Y") }}</td>
				<td>{{Donne.titre}}</td>
				<td>{{Donne.dateTimeDebut|date("d/m/Y") }}</td>
				<td>{{Donne.dateTimeFin|date("d/m/Y") }}</td>
				<td>{{Donne.participantNbAdultes}}</td>
                <td>{{Donne.participantNbEnfants}}</td>
                <td>
				    {% for pay in Donne.pays %}
                        {{ pay.Name }}
						<hr/>
                    {% endfor %}
				</td>
               
				<td class="text-center">
					<a href="{{ path("admin_voyages_modif", {id: Donne.id}) }}" class="btn blue">Modifier</a>
				</td>
				<td class="text-center">
                    <a href="{{ path("admin_voyages_supprimer", {id: Donne.id}) }}" class="btn red">Supprimer</a>
                </td>
			</tr>
        {% endfor %}
		</tbody>
		<thead>
		<tr>
			<th>
				<input type="checkbox" onchange="selectForm(this);"  checked name="selectAll" value="1"/>
			</th>
			<th colspan=5>
				<a onclick="return validateForm();" class="btn red">Supprimer tous les éléments selectionné</a>
			</th>
		</tr>
		</thead>
	</table>
{% else %}
	<div class='container'>
		Aucune donnée actuellement. 
	</div>
{% endif %}
{% if find is null  %}
	<div class='container'>
	/{{ find }}/
		<b><a href='{{ path("admin_voyages_home") }}'><- Retour à toute la liste</a></b>
	</div>
{% endif %}
<script>
  function validateForm() {
		console.log("validateForm");
		var table = document.getElementById ('dataTable');
		var checkboxes = table.querySelectorAll('input[type=checkbox]');
		let list = "";

	  	console.log("checkboxes.length", checkboxes.length);
		for (var i = 0; i < checkboxes.length; i++){
			//checkboxes[i].checked = val;
			var val = checkboxes[i].checked;
			//console.log("checkboxes[i] value", checkboxes[i].value);
			//console.log("checkboxes[i] val", val);
			if(val == true){
				list = list + "-" +  checkboxes[i].value;
				//console.log("checkboxes[i] val", checkboxes[i].value);
			}
			
		}
	
	//console.log("list : ", list);
		post('{{ path("admin_voyages_supp") }}', {list: list});

	}

	function selectForm(checkbox) {
	  	console.log("selectForm");

		var table = document.getElementById('dataTable');
		var checkboxes = table.querySelectorAll('input[type=checkbox]');
		let list = "";
		let checkEtat = true;

		var chkBox = document.getElementById('selectAll');
		if (checkbox.checked)
		{
			checkEtat = true;
		} else {
			checkEtat = false;
		}
		

		console.log("checkboxes.length", checkboxes.length);
		for (var i = 0; i < checkboxes.length; i++){
			checkboxes[i].checked = checkEtat;   
		}


	}

/**
 * sends a request to the specified url from a form. this will change the window location.
 * @param {string} path the path to send the post request to
 * @param {object} params the parameters to add to the url
 * @param {string} [method=post] the method to use on the form
 */
function post(path, params, method='post') {

  // The rest of this code assumes you are not using a library.
  // It can be made less verbose if you use one.
  const form = document.createElement('form');
  form.method = method;
  form.action = path;

  for (const key in params) {
    if (params.hasOwnProperty(key)) {
      const hiddenField = document.createElement('input');
      hiddenField.type = 'hidden';
      hiddenField.name = key;
      hiddenField.value = params[key];

      form.appendChild(hiddenField);
    }
  }

  document.body.appendChild(form);
  form.submit();
}
</script>

{% endblock %}